### ISSUE TITLE
support only python 3.5 and up

### ISSUE THREAD

**Issue by fizyk** [ClearcodeHQ/pytest-rabbitmq#114]

**Comment by sotanodroid** [comment]
Please add python 3.7 support

**Comment by fizyk** [comment]
@sotanodroid are there any issues on python3.7 at the moment?

**Comment by fizyk** [comment]
because it is tested against python 3.7 already

**Comment by sotanodroid** [comment]
@fizyk Oh sorry, was my bad. I mistested this package in my project in wrongly thought that it have not support for 3.7/ If you don't mind i would delete previous comment
