### ISSUE TITLE
Cannot See Any Examples?

### ISSUE THREAD

**Issue by ozgurakyazi** [ClearcodeHQ/pytest-rabbitmq#149]
### What action do you want to perform
Be able to see some examples of this plugin.

### What are the results
Cannot find any documentation about this. In the readme file, there is only example of the configuration, but not an example, or a the usage of the plugin.

### What are the expected results
I would like to see some explanations and examples about this plugin. If I could not find any, can you help me with this?

Best,

**Comment by fizyk** [comment]
Maybe tests will help: 
https://github.com/ClearcodeHQ/pytest-rabbitmq/blob/master/tests/test_rabbitmq.py
You've got two pytest fixtures, you basically most of the time need to include only the client fixture

**Comment by fizyk** [comment]
haven't been adding example usage since it's straightforward as pytest, and the fixture returns a connection to rabbitmq

**Comment by ozgurakyazi** [comment]
> Maybe tests will help:
> https://github.com/ClearcodeHQ/pytest-rabbitmq/blob/master/tests/test_rabbitmq.py
> You've got two pytest fixtures, you basically most of the time need to include only the client fixture

This solves my problem. 


> haven't been adding example usage since it's straightforward as pytest, and the fixture returns a connection to rabbitmq

I believe examples could be still be useful. 

Thank you :)

**Comment by pheanex** [comment]
I'd also recommend adding a simple example to help new users better understand how this plugin works (Similar how other pytest-plugins do)
