### ISSUE TITLE
Fails to start RabbitMQ node

### ISSUE THREAD

**Issue by albireox** [ClearcodeHQ/pytest-rabbitmq#221]
For the last couple months `pytest-rabbitmq` fails to start. This seems to be somehow related to starting the RabbitMQ node. It times out with error

```
Configuring logger redirection

BOOT FAILED
===========
Error during startup: {error,
                          {failed_to_cluster_with,
                              ['pytest-rabbitmq-test@AlbireoPro'],
                              "Mnesia could not connect to any nodes."}}

^CKernel pid terminated (application_controller) ({application_start_failure,rabbit,{{failed_to_cluster_with,['pytest-rabbitmq-test@AlbireoPro'],"Mnesia could not connect to any nodes."},{rabbit,start,[

Crash dump is being written to: /usr/local/var/log/rabbitmq/erl_crash.dump...done
```

In some cases changing the `rabbitmq_node` parameter makes it work for a few test runs, but eventually it fails again. This happens only in macOS with `rabbitmq` installed using Homebrew. The same tests do work fine in a GitHub Action that uses Ubuntu 20.04.

**Comment by fizyk** [comment]
@albireox I have little expierience using macos (used it for about a year only for tasks I had to use it, still my main system was ubuntu/linux) 

Adding the macos runs would be required to handle the task, maybe a simple wait or retry would be sufficient, or it could be some debugging required on what's going on underneath (logs, that dump). But As I said, I have no experience coding on macos let alone running rabbitmq to solve it myself. I'd welcome any help, or fixes to handle macos builds better here though.

**Comment by fizyk** [comment]
I'd guess that probably 317 is related
