### ISSUE TITLE
RabbitMQ fills the temporary directory – pytest-rabbitmq doesn't clean up after itself

### ISSUE THREAD

**Issue by akaihola** [ClearcodeHQ/pytest-rabbitmq#266]
### What action do you want to perform
Repeatedly run a test suite which uses the `rabbitmq_proc` fixture.

### What are the results
RabbitMQ runs out of disk space.

### What are the expected results
RabbitMQ should run fine and not leave huge amounts of data in temporary filesystems.

---

The reason for this seems to be that `pytest-rabbitmq` uses Python's [tempfile.gettempdir()](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir) to get a directory for the RabbitMQ server to store its data (see [src/pytest_rabbitmq/factories/process.py:98](https://github.com/ClearcodeHQ/pytest-rabbitmq/blob/825537961f692a61bf2ad136801dfafa45458713/src/pytest_rabbitmq/factories/process.py#L98)).

On my system, `gettempdir()` returns `/run/user/1000` which has 3.2 GiB of total space. However, after I've run my test suite for a half dozen times while sometimes debugging for a couple of hours, that filesystem has been filled with `rabbitmq.<pid>` directories. They typically eat 0.5 GiB each.

The problem wasn't easy to spot, and `pytest-rabbitmq` could help by either cleaning up the data directory or letting me know loud and clear that it left lots of data on disk.

**Comment by akaihola** [comment]
Here's the fixture I use as a work-around for this problem:
```python
@pytest.fixture
def rabbitmq_server(rabbitmq_proc):
    tempdir = Path(rabbitmq_proc._envvars["RABBITMQ_MNESIA_BASE"]).parent
    try:
        # `aiopika` uses the `AMQP_PORT` environment variable, patch that:
        with patch.dict(os.environ, {"AMQP_PORT": str(rabbitmq_proc.port)}):
            yield
    finally:
        rmtree(tempdir, ignore_errors=True)
```

**Comment by fizyk** [comment]
We could attempt to get the directory size and print message I suppose. We can also I think pretty format that message at the end of the tests 🤔 

I'd want to also migrate the temporary path handling to tmp_path_factory for this.
