### ISSUE TITLE
RabbitMQ will not start if selected port value is too large

### ISSUE THREAD

**Issue by phillipuniverse** [ClearcodeHQ/pytest-rabbitmq#317]
### What action do you want to perform

Start the rabbitmq server reliably. The RabbitMQ server randomly fails to start up. I dug in and noticed an `erl_crash.dump` file gets created. Looking into this and with some googling, this is the 'Slogan', which supposedly is the error message:

```
Slogan: Kernel pid terminated (application_controller) ({application_start_failure,rabbitmq_prelaunch,{{shutdown,{failed_to_start_child,prelaunch,{invalid_dist_port_range,65958}}},{rabbit_prelaunch_app,start,[normal,[]]}}})
```

The important part of this is `{invalid_dist_port_range,65958}`. It turns out that RabbitMQ has a maximum port number of 65535 [as defined here](https://github.com/rabbitmq/rabbitmq-server/blob/1a6f81b584b3723870dec0ed1e0f714aa55fb80c/deps/rabbit/apps/rabbitmq_prelaunch/src/rabbit_prelaunch_dist.erl#L99-L102).

Not sure if this happens regularly on Linux but it happens a lot on MacOS (2019 Intel, Ventura 13.3.1).

### What are the results

Not started reliably.

### What are the expected results

Should be a simple fix to limit the `port_for` call in this part if not otherwise specified by the user:

https://github.com/ClearcodeHQ/pytest-rabbitmq/blob/dcd96a4ddce881b16c63a0794c152b1a3a36d001/src/pytest_rabbitmq/factories/process.py#LL96C32-L96C36

**Comment by phillipuniverse** [comment]
The fix was pretty easy:

```python
from pytest_rabbitmq import factories

factories.rabbitmq_proc(port=(1, 65535))
```

**Comment by fizyk** [comment]
Linux also is affected by something similar, it actually states that the distribution port is already used:
https://github.com/ClearcodeHQ/pytest-rabbitmq/actions/runs/5187634162/jobs/9350236844

🤔 is there a way to manually set that for RabbitMQ?
