### ISSUE TITLE
Deprecation on logsdir always raised

### ISSUE THREAD

**Issue by phillipuniverse** [ClearcodeHQ/pytest-rabbitmq#356]
### What action do you want to perform

Use `pytest-rabbitmq` with no DeprecationWarning raised.

### What are the results

I get a deprecation warning:

```
DeprecationWarning: rabbitmq_logsdir and --rabbitmq-logsdir config option is deprecated, and will be dropped in future releases. All fixture related data resides within /private/tmp/pytest/pytest-rabbitmq-_rabbitmq_server0
```

Here's what is happening:

<img width="1308" alt="image" src="https://github.com/ClearcodeHQ/pytest-rabbitmq/assets/684275/a9e241c9-9c4a-484c-8753-834a67f6d816">

If you look at the 'watch' variables, you can see the discrepancy between `request.config.getoption` and `request.config.getini`. Since `request.config.getini` returns an empty string, the final value for `logsdir` in the `config` in the `get_config` function returns `Path('')`, and `Path` with an empty string assumes the current directory (apparently).

You can then see how when we check the truthiness of `rabbit_logpath`, because `config['logsdir']` is truthy (it's a real path for the current directory), we warn:

<img width="728" alt="image" src="https://github.com/ClearcodeHQ/pytest-rabbitmq/assets/684275/8d775d94-e4ee-4b14-9520-e8bdf58e2fe6">

I have no overrides to the `rabbitmq_logpath` configuration setting.

I am using Pytest 7.3.2 and pytest-rabbitmq 3.0.1.

### What are the expected results

No DeprecationWarning raised

**Comment by phillipuniverse** [comment]
Looks like the main issue was caused by the refactoring in https://github.com/ClearcodeHQ/pytest-rabbitmq/commit/9f60df7476d4eb7f97b0b81360352a29ed94b780 with a few incorrect assumptions.

The other issue is that without using the tmpdir there are some other permission-related issues with starting up the server and writing to the log file, startup usually fails.

**Comment by fizyk** [comment]
@phillipuniverse 3.0.2 released
